# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-20 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correction', '0002_auto_20170720_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='watcategory',
            name='example',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
