# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-20 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correction', '0003_watcategory_example'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataneedscorrection',
            options={'verbose_name_plural': 'Data needs to be corrected '},
        ),
        migrations.AlterModelOptions(
            name='datavalidated',
            options={'verbose_name_plural': 'Validated Data'},
        ),
        migrations.AlterModelOptions(
            name='watcategory',
            options={'verbose_name_plural': 'Word Analogy Reasoning Task Categories'},
        ),
    ]
