# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-20 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correction', '0004_auto_20170720_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataneedscorrection',
            name='status',
            field=models.CharField(default='default', max_length=20),
            preserve_default=False,
        ),
    ]
