# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-20 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correction', '0005_dataneedscorrection_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datacorrected',
            options={'verbose_name_plural': 'Data Corrected'},
        ),
    ]
