# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-22 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('correction', '0006_auto_20170720_2339'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='dataneedscorrection',
            managers=[
                ('datum', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='dataneedscorrection',
            name='status',
            field=models.CharField(choices=[('default', 'Default'), ('corrected', 'Corrected'), ('validated', 'Validated')], max_length=20),
        ),
    ]
