# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-22 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correction', '0007_auto_20170722_2040'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='dataneedscorrection',
            managers=[
            ],
        ),
    ]
