# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-21 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0004_auto_20170722_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmenu',
            name='isVisible',
            field=models.BooleanField(default=False),
        ),
    ]
